repository:
  homepage: https://event-emitter.esm.is/
  description: <200 bytes type safe extendable event emitter / pubsub class
  has_wiki: false
labels:
  - name: ðŸž bug
    color: ee0701
    description: this isn't working as expected
    oldname: bug
  - name: âœ¨ feature request
    color: fbca04
    description: a new feature request
  - name: âš¡ï¸ enhancement
    color: a2eeef
    description: improvement over an existing feature
    oldname: enhancement
  - name: â™¦ï¸ need repro
    color: c9581c
    description: the issue needs a reproduction for further investigation
  - name: ðŸ§‘â€ðŸ’» has workaround
    color: 2139c4
    description: has a temporary fix to get around the problem
  - name: ðŸ‘ contribution welcome
    color: 0e8a16
    description: others are welcome to implement/fix this
  - name: ðŸ”¹ typescript
    color: 3178c6
    description: issue related to types
  - name: ðŸ’¬ discussion
    color: 4935ad
    description: topic that requires further discussion
    oldname: discussion
  - name: ðŸ“š docs
    color: 8be281
    description: related to documentation
    oldname: documentation
  - name: 1ï¸âƒ£ good first issue
    color: 7057ff
    description: this should be manageable for new-comers
    oldname: good first issue
  - name: ðŸ™ help wanted
    color: 008672
    description: help in this issue is welcome
  - name: ðŸš« wontfix
    color: ffffff
    description: this issue won't be fixed
    oldname: wontfix
